<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Password and Confirm password must be same</name>
   <tag></tag>
   <elementGuidId>dabb8e0c-1171-4b36-8b58-7c26ae628fd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='confirmPassword-error-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#confirmPassword-error-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Password and Confirm password must be same&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>3d78c0b9-8502-4c4f-9734-50d54cade36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeSmall MuiFormHelperText-contained MuiFormHelperText-filled css-18emikf</value>
      <webElementGuid>406e5106-bf1f-4f7d-9394-2148b08a9c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmPassword-error-text</value>
      <webElementGuid>db4a6065-ffe0-4b43-9a69-b8f9a84017ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>efbcdd82-0ee2-4008-90b1-a2996b6cf5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password and Confirm password must be same</value>
      <webElementGuid>8790c72e-c6df-44b7-9e63-3b5ac9bcdfe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmPassword-error-text&quot;)</value>
      <webElementGuid>c7d304d1-203e-466f-89aa-f68e98b26cba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='confirmPassword-error-text']</value>
      <webElementGuid>e4c7d57e-f620-4870-8573-1eda39dda33b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerForm']/div/div/div[3]/div[2]/div/div/div[2]/p</value>
      <webElementGuid>d1a913f1-0a79-4700-a204-4d1d09a813d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[6]/following::p[1]</value>
      <webElementGuid>4b462a9c-8d83-4963-83a0-ef4b67c66a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Password'])[1]/following::p[1]</value>
      <webElementGuid>109bfdbc-6921-4bde-a1d1-b93353001442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone'])[1]/preceding::p[1]</value>
      <webElementGuid>d5b4d239-da4d-4fa9-b8ac-3f22df737422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[7]/preceding::p[1]</value>
      <webElementGuid>9662e88f-6df9-46ab-93e0-a0aa0df1bf19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Password and Confirm password must be same']/parent::*</value>
      <webElementGuid>e3a2b89e-eb56-4a49-8447-48af47416a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/p</value>
      <webElementGuid>2d526466-1775-495f-9962-faa98c2923c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'confirmPassword-error-text' and (text() = 'Password and Confirm password must be same' or . = 'Password and Confirm password must be same')]</value>
      <webElementGuid>a276d71d-6a5d-4d82-a47e-2abb464379cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
