<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_2023_1</name>
   <tag></tag>
   <elementGuidId>3a8d13a0-574f-4332-a5f5-f47d53c49968</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.MuiPickersYear-yearButton.Mui-selected.css-1hmgxzr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[145]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=radio[name=&quot;2023&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e07bd107-f956-46e7-a7f9-6c31cf859987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>808c5260-502f-4c40-84f6-e8b274854ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>3f61dae2-af06-4658-890f-cf32cc7e43ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>40db6a6c-8163-42e9-95ed-eb86780a9334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>45960c8e-b006-496a-8e8c-9c4f485580aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiPickersYear-yearButton Mui-selected css-1hmgxzr</value>
      <webElementGuid>811b98a4-9a8d-4676-8b55-b26bdd2b72a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2023</value>
      <webElementGuid>7f2ce20d-22bf-4a0a-9d5e-08a6d8535e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiPopper-root MuiPickersPopper-root css-1mtsuo7&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation8 MuiPickersPopper-paper css-1c08mdw&quot;]/div[@class=&quot;MuiPickersLayout-root css-192l38i&quot;]/div[@class=&quot;MuiPickersLayout-contentWrapper css-lz05jy&quot;]/div[@class=&quot;MuiDateCalendar-root css-5oi4td&quot;]/div[@class=&quot;MuiPickersFadeTransitionGroup-root MuiDateCalendar-viewTransitionContainer css-1h73gvd&quot;]/div[1]/div[@class=&quot;MuiYearCalendar-root css-kiu2gm&quot;]/div[@class=&quot;MuiPickersYear-root css-j9zntq&quot;]/button[@class=&quot;MuiPickersYear-yearButton Mui-selected css-1hmgxzr&quot;]</value>
      <webElementGuid>7b04548b-1506-4cdc-9e3f-2dca5e72d0cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[145]</value>
      <webElementGuid>39816432-3fc4-436f-a687-327021bb8e62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='October 2023'])[1]/following::button[127]</value>
      <webElementGuid>065ff6e4-f7fb-48d7-9313-bf34ce32e0a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::button[127]</value>
      <webElementGuid>c38419c9-288d-489b-a4c8-1f9d5cc1c6de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2023']/parent::*</value>
      <webElementGuid>bf0ae9ce-53b2-46a1-aa56-1a1c58c8ce87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[124]/button</value>
      <webElementGuid>ea7e6f0b-61ef-4b90-b97c-4f55acc68daf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '2023' or . = '2023')]</value>
      <webElementGuid>9334cb67-4027-472c-8ad6-44381441c9dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
