<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_2024  NJ TRANSIT All Rights Reserved</name>
   <tag></tag>
   <elementGuidId>13f18fb9-938d-45e4-9f33-9ca23d74efc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='footerDescBox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#footerDescBox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#footerDescBox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6e2c816e-315e-4a10-b0c3-b6426352dd82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-xi606m</value>
      <webElementGuid>2d35b6b5-3462-4155-af43-7dd7351ac32a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>footerDescBox</value>
      <webElementGuid>4e699d7f-9a38-4e01-9545-41e6568395d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2024 @ NJ TRANSIT All Rights Reserved.</value>
      <webElementGuid>5e9fdab5-7295-4a93-a092-703b87444aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footerDescBox&quot;)</value>
      <webElementGuid>bdd7b379-54e7-47af-afa7-5663ad71c09c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='footerDescBox']</value>
      <webElementGuid>0416682d-46ae-490e-8e53-0302e50f28ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='footerDescGrid']/div</value>
      <webElementGuid>51f7df12-4f49-4d0e-b809-5770aac8ac65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRX. History'])[1]/following::div[6]</value>
      <webElementGuid>6ba46d31-1712-43f3-a534-07c9750cd80e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACTIVE'])[1]/following::div[11]</value>
      <webElementGuid>8c2bd599-7eac-43c6-a424-704e91858084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help &amp; Support'])[1]/preceding::div[1]</value>
      <webElementGuid>37ccb08a-52c6-436b-b971-6a3500f6ae76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/preceding::div[1]</value>
      <webElementGuid>5189bf08-2148-458e-abc2-9a6ed22dcd6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div/div/div/div</value>
      <webElementGuid>b0e6d1d2-d002-4bbd-9781-4493de6331e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'footerDescBox' and (text() = '2024 @ NJ TRANSIT All Rights Reserved.' or . = '2024 @ NJ TRANSIT All Rights Reserved.')]</value>
      <webElementGuid>9fe1b886-93fd-46f8-91a7-dc238c8b8e1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
