<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_ACTIVE_Card</name>
   <tag></tag>
   <elementGuidId>5264aca9-7dab-477e-a11a-bd57d541d9e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#visaCard</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Visa card&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4ef95d7e-1458-4ac7-a0f0-ebb85cc6efcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-xcqecp</value>
      <webElementGuid>fe2c26bc-611b-49a0-8b63-074167fa80e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visaCard</value>
      <webElementGuid>f14e768a-9585-47af-aafd-68a2a9a4acfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Visa card</value>
      <webElementGuid>01878df1-2b58-4efc-82e6-ba599ce7dd7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/njt-web/static/media/visa_card.d6157c0bb3472d9c1c7b.png</value>
      <webElementGuid>52e059b8-ea35-4cbc-9863-5bba63f168d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visaCard&quot;)</value>
      <webElementGuid>7ec5cd8f-8c16-4c45-b09a-dbe096831db4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='visaCard']</value>
      <webElementGuid>6c80e1ba-059b-4a51-ae7e-a8d2a1fb8a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboardCard']/div/div/div[2]/div/img</value>
      <webElementGuid>a86b819b-1aa5-4498-a14f-7fa629af2ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Visa card']</value>
      <webElementGuid>883b57ad-d6d5-4e0a-9ef6-5ae8fcf3a69d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>35266466-7fa4-4659-9169-169dab07023e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'visaCard' and @alt = 'Visa card' and @src = '/njt-web/static/media/visa_card.d6157c0bb3472d9c1c7b.png']</value>
      <webElementGuid>d996167e-2420-4b05-abe9-40c7eb02a408</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
