<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_ACTIVE_masterCard</name>
   <tag></tag>
   <elementGuidId>a8f80cac-c7d7-4554-9d31-8e925b8bbcc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#masterCard</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='masterCard']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Master card&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e919c4f1-9a58-4d64-b215-99bcd3a91953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-xcqecp</value>
      <webElementGuid>22dd017f-d02a-43a7-b2d9-91a4c06482a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>masterCard</value>
      <webElementGuid>4f118876-0838-4a0e-a8dd-ab7a33766124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Master card</value>
      <webElementGuid>37bd185a-a0bf-47d9-8467-a79905d99d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/njt-web/static/media/master_card.7c6c3e9c8972a5588468.png</value>
      <webElementGuid>3fbab7d6-84a4-48cc-852e-fe6b43b2adfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;masterCard&quot;)</value>
      <webElementGuid>6473bd8a-13cd-422a-bcc2-38266b977483</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='masterCard']</value>
      <webElementGuid>5ddd34d3-4184-4e07-b827-65f709418398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboardCard']/div/div/div[2]/div/img</value>
      <webElementGuid>e19fff05-2a4f-4f6d-8af1-d94f9fa389d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Master card']</value>
      <webElementGuid>9e7f8919-6a24-4c4f-bc68-50efad5ca860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>53ac3c90-8900-4c65-8103-fadb01945a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'masterCard' and @alt = 'Master card' and @src = '/njt-web/static/media/master_card.7c6c3e9c8972a5588468.png']</value>
      <webElementGuid>fdc8cceb-d8b0-4a31-9edc-d874ead886de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
