<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_ACTIVE_unionpayCard</name>
   <tag></tag>
   <elementGuidId>86c96924-2f6c-45aa-a246-b533bd3d8192</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#unionpayCard</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='unionpayCard']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Union Pay card&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8f8ac8fa-b1da-4052-b150-32dc4bcde08b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-xcqecp</value>
      <webElementGuid>698d5ce2-91b7-4969-98c7-2758487b071c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unionpayCard</value>
      <webElementGuid>cb4587ab-8971-4e71-a7dc-b799eb451c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Union Pay card</value>
      <webElementGuid>3a1af136-e38f-45fd-ac8a-420cfee4cc1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/njt-web/static/media/unionpay_card.5159651291a278d4a2d5.png</value>
      <webElementGuid>573970e6-e9aa-4633-8c77-7a4628d95b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unionpayCard&quot;)</value>
      <webElementGuid>2aac0521-857f-49d8-b0bf-563633270d47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='unionpayCard']</value>
      <webElementGuid>caa6ebfb-b052-4c40-ae43-62df73f7e77b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboardCard']/div/div/div[2]/div/img</value>
      <webElementGuid>41f3b94f-0cf2-423a-a849-cd5ab8db0bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Union Pay card']</value>
      <webElementGuid>d87ae7c0-38bf-4a05-a6db-ea75f387cf45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>a7d8caa6-e177-4d1f-a348-93e161a60794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'unionpayCard' and @alt = 'Union Pay card' and @src = '/njt-web/static/media/unionpay_card.5159651291a278d4a2d5.png']</value>
      <webElementGuid>079a3fd0-f966-4ce0-9473-e5329d31498f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
