<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_ACTIVE_discoverCard</name>
   <tag></tag>
   <elementGuidId>3d869f33-ecee-4dab-8de2-bb229bc3996c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#discoverCard</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='discoverCard']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Discover card&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>52d50919-10d9-46ed-b18a-e55769ee82d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-xcqecp</value>
      <webElementGuid>5bd56f42-2f40-468b-82bf-14fddbf9164c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>discoverCard</value>
      <webElementGuid>3b929349-6a79-48ff-b082-967dd875fd3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Discover card</value>
      <webElementGuid>9ff89a98-24e6-4faf-879d-d3c6100295c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/njt-web/static/media/discover_card.46d26c2c300958f29379.png</value>
      <webElementGuid>ebf28983-c502-4a9e-8385-c441646670e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;discoverCard&quot;)</value>
      <webElementGuid>19e7fed1-e0eb-4442-a2be-4b52a943bac7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='discoverCard']</value>
      <webElementGuid>8a264584-fc6a-46a4-97bf-c1a5586e953f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboardCard']/div/div/div[2]/div/img</value>
      <webElementGuid>6f88b5ef-aa51-4d93-8354-c919c9d1ed10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Discover card']</value>
      <webElementGuid>250294f1-0ad2-4aaa-8e9f-110685cc32ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>310eb9f2-5a38-4583-96fa-5cca691b1946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'discoverCard' and @alt = 'Discover card' and @src = '/njt-web/static/media/discover_card.46d26c2c300958f29379.png']</value>
      <webElementGuid>a80d1922-1e43-484e-b485-e535ecd87e62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
