<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Card Account Id is required</name>
   <tag></tag>
   <elementGuidId>d6de97a6-340b-4d3f-89a7-d578079c5018</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'cardAccountId-error-text' and (text() = 'Card Account Id is required' or . = 'Card Account Id is required')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='cardAccountId-error-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cardAccountId-error-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Card Account Id is required&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>93f15a7e-59af-4232-a3db-89e47114be66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeSmall MuiFormHelperText-contained css-18emikf</value>
      <webElementGuid>5d0011d1-7ce4-4b63-bac3-6273fa614cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cardAccountId-error-text</value>
      <webElementGuid>db17a1a2-aeb3-4b9b-b1bd-c12d0ab7afeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>86a3f03a-9c05-45be-ac73-507d2d9ae03d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Card Account Id is required</value>
      <webElementGuid>20ce1cbc-b6c1-429c-8af7-256fe924923c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cardAccountId-error-text&quot;)</value>
      <webElementGuid>d3e32331-0116-44eb-9d8e-41c39d590815</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='cardAccountId-error-text']</value>
      <webElementGuid>b5ae0789-ccee-41d0-8970-72631f811c36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='accRegistrationForm']/div/div/div/div[2]/p</value>
      <webElementGuid>4e4b324e-c50d-4005-bb27-af5f5169f7fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::p[1]</value>
      <webElementGuid>63ec34d5-8e42-4e3f-82eb-252d4a9fbacc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Account Id'])[1]/following::p[1]</value>
      <webElementGuid>b64f8903-fe5c-41ad-be7a-9ed14ccf50cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register Payment'])[1]/preceding::p[1]</value>
      <webElementGuid>85c32137-dd35-4b6b-b1b4-9b708909eb77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help &amp; Support'])[1]/preceding::p[1]</value>
      <webElementGuid>eaaab128-eb58-48ba-9c98-3d8e8e8611ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Card Account Id is required']/parent::*</value>
      <webElementGuid>fd6ff9ae-850b-477c-99b1-aa00ab10872b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>5618c10d-41ff-4cdc-bbab-2d8c06c98897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'cardAccountId-error-text' and (text() = 'Card Account Id is required' or . = 'Card Account Id is required')]</value>
      <webElementGuid>5d6b7dd0-4a26-4d75-abeb-2d1810f9ff72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
