<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_AccountId</name>
   <tag></tag>
   <elementGuidId>0fb608b0-a4ff-477e-969c-9b2cbe17c648</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#5ENAQU2M</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;5ENAQU2M&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>558f99b9-aebd-4899-96eb-fddfd841c89f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-value css-5xcydg</value>
      <webElementGuid>4609460d-376d-49a5-bfd5-8d2d9cf89dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>5ENAQU2M</value>
      <webElementGuid>f11d15cf-9a2c-4dd0-be36-67b98c9fc5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5ENAQU2M</value>
      <webElementGuid>ef9e391a-08d1-4cc1-bef6-27855c3f7018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;5ENAQU2M&quot;)</value>
      <webElementGuid>a20f5f48-87db-49ca-b85a-ba77c39f5b9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='5ENAQU2M']</value>
      <webElementGuid>133a92d0-c8ca-4f73-a1b2-3ecc71af5e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboardCard']/div/div/div/div/div/table/tbody/tr/td[2]/span</value>
      <webElementGuid>8aed3513-9018-46b2-9832-55f78eab8aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Id'])[1]/following::span[1]</value>
      <webElementGuid>4e051341-0d68-4686-b90d-4f6c3ebd2596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::span[2]</value>
      <webElementGuid>33e25010-b1a0-4590-9346-729b62fe0d41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Number'])[1]/preceding::span[1]</value>
      <webElementGuid>78224da1-8d73-430c-b508-b1f4d20a0bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XXXX-XXXX-XXXX-1032'])[2]/preceding::span[2]</value>
      <webElementGuid>a1fe74a4-2a19-43e1-a1fa-f6f1cf485c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='5ENAQU2M']/parent::*</value>
      <webElementGuid>b6322073-705e-4b36-a654-e0a53a0aff11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/span</value>
      <webElementGuid>d807d991-e196-405a-876d-4dd84a139b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '5ENAQU2M' and (text() = '5ENAQU2M' or . = '5ENAQU2M')]</value>
      <webElementGuid>e228b47f-bd5e-4876-b694-0c21b29d9c13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
