<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_02212024</name>
   <tag></tag>
   <elementGuidId>99a1f135-f435-466c-ae22-7f94436a1b1c</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='02/21/2024']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = '02/21/2024' and (text() = '02/21/2024' or . = '02/21/2024')]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;02/21/2024&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9be36fd1-ea7c-40d0-b2bc-53080ff4ab32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-value css-5xcydg</value>
      <webElementGuid>bf8a34a4-2e85-49f9-a026-ab72a266d49a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>02/21/2024</value>
      <webElementGuid>450ff394-a27e-4fb2-b6a3-3b76fdc41e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>02/21/2024</value>
      <webElementGuid>30abc7fa-c18d-4423-bbc6-7efd06d599a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;02/21/2024&quot;)</value>
      <webElementGuid>9992bb0c-5fd3-47a6-836d-3f4c6b1a8aed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='02/21/2024']</value>
      <webElementGuid>b7b84e0b-52b0-4463-be04-ddf0ca39fb43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboardCard']/div/div/div/div/div/table/tbody/tr[5]/td[2]/span</value>
      <webElementGuid>32b4532a-44d3-4b7a-a638-f7f90e7655dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Trip'])[1]/following::span[1]</value>
      <webElementGuid>1f207b55-d4b9-4a4e-9718-1f859940f8c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contactless Card'])[1]/following::span[2]</value>
      <webElementGuid>1fdbe589-62b7-4b09-8c61-439b90812b11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Trip'])[1]/preceding::span[1]</value>
      <webElementGuid>1e44f626-a33b-43ec-9dc3-ef923823396c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Status'])[1]/preceding::span[3]</value>
      <webElementGuid>6a983f8f-bdc8-40d1-93e3-597a4fa945d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='02/21/2024']/parent::*</value>
      <webElementGuid>04389901-c62d-4439-a2f3-badf4f33937c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/span</value>
      <webElementGuid>8188a426-7cf3-455b-99da-4127da4cf479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '02/21/2024' and (text() = '02/21/2024' or . = '02/21/2024')]</value>
      <webElementGuid>58cf298c-90d9-4f13-ad20-9a5efca8c62a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
