<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_02282029</name>
   <tag></tag>
   <elementGuidId>c15792c9-7f0e-4cb9-b562-2689fccd47a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = '02/28/2029' and (text() = '02/28/2029' or . = '02/28/2029')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dashboardCard']/div/div/div/div/div/table/tbody/tr[3]/td[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;02/28/2029&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>be57b59d-95c9-428b-aa52-e5bb628b55d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-value css-5xcydg</value>
      <webElementGuid>69846714-2169-473a-a06c-e394da20535c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>02/28/2029</value>
      <webElementGuid>8d25a4af-ef3e-41ba-8b34-e1b8d2b30d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>02/28/2029</value>
      <webElementGuid>ab093288-1eca-43bb-82f2-0e233cffd5fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;02/28/2029&quot;)</value>
      <webElementGuid>4641e686-00ef-4010-a20c-f062c9b82643</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='02/28/2029']</value>
      <webElementGuid>5ad3557b-f985-4b46-bd94-737ead87cca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboardCard']/div/div/div/div/div/table/tbody/tr[3]/td[2]/span</value>
      <webElementGuid>617b0495-a287-48a1-835f-e9da2c5d7541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exp. Date'])[1]/following::span[1]</value>
      <webElementGuid>81a459fe-350e-4c49-8068-a09cfd81b583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XXXX-XXXX-XXXX-0286'])[2]/following::span[2]</value>
      <webElementGuid>830be7a1-3160-4cf2-b5ef-5bf0f96d746a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Media Type'])[1]/preceding::span[1]</value>
      <webElementGuid>7f426a6f-bad2-45aa-9866-a6e6cb5dbf4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contactless Card'])[1]/preceding::span[2]</value>
      <webElementGuid>bc0d3e44-97ba-4748-8fe4-58a8e6be52c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='02/28/2029']/parent::*</value>
      <webElementGuid>0c306b65-0e2f-4883-a157-a3635af21f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/span</value>
      <webElementGuid>0e0e61be-b4d4-44f3-ac86-008d34642582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '02/28/2029' and (text() = '02/28/2029' or . = '02/28/2029')]</value>
      <webElementGuid>dde8c2a6-b3d7-4776-9301-7966e28b0302</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
