<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Buy Tickets</name>
   <tag></tag>
   <elementGuidId>f1da0458-e2f4-468d-b718-84e97666b760</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buyTicketBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='buyTicketBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Buy Tickets&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e0c01d32-1dda-42b3-aed6-8eee0299b574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedSecondary MuiButton-sizeSmall MuiButton-containedSizeSmall MuiButton-colorSecondary MuiButton-root MuiButton-contained MuiButton-containedSecondary MuiButton-sizeSmall MuiButton-containedSizeSmall MuiButton-colorSecondary css-eoy7ye</value>
      <webElementGuid>93e93ee4-36b7-44fc-b1fa-7b42bbf87bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ff4346b1-61c6-497c-a065-fe7068d28d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8df2b3d9-bb51-47b5-9cab-82bc1f360571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buyTicketBtn</value>
      <webElementGuid>caf35004-0664-4e98-aea0-aa28920e56fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Buy Tickets</value>
      <webElementGuid>843fc450-cbf1-48cc-ae3b-73ed619c1dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Buy Tickets</value>
      <webElementGuid>d73fa4be-2bd6-4cfe-b8cc-891d8835780e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5ee69890-88cb-4c29-b55f-5345ef389d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-theme</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>6ce34454-4262-495a-96df-76c8037c4736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buy Tickets</value>
      <webElementGuid>5b571bca-e00f-449f-a14a-111d4b022b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buyTicketBtn&quot;)</value>
      <webElementGuid>e2891a52-f7ad-4ab6-a3e7-2270c94b28e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='buyTicketBtn']</value>
      <webElementGuid>5a0296b7-344a-4ee8-aa82-4851d53722a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'buyTicketBtn' and @title = 'Buy Tickets' and (text() = 'Buy Tickets' or . = 'Buy Tickets')]</value>
      <webElementGuid>d62081c0-ff63-48fa-abd3-39c6c90d5d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboardCard']/div/div[2]/div/div[2]/button</value>
      <webElementGuid>ac8eeb58-e01a-461a-9566-bbb43edb674e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>f75edd92-ae1a-424b-b04e-fffd1a723aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Value'])[1]/following::button[1]</value>
      <webElementGuid>a86df19e-7243-4403-af36-dcf295272381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UNREGISTER CARD'])[1]/following::button[2]</value>
      <webElementGuid>7226878f-497b-40b3-8f07-c16a1626457d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto Reload'])[2]/preceding::button[1]</value>
      <webElementGuid>b1c61a74-5e0e-4ec6-a86c-dd0e083fe31b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRX. History'])[1]/preceding::button[2]</value>
      <webElementGuid>7be886b8-c504-49e0-a3a8-8de0955cc881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buy Tickets']/parent::*</value>
      <webElementGuid>dd17fd19-e8a3-4439-bf64-44032de38bfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
