<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ticketsTab</name>
   <tag></tag>
   <elementGuidId>581f86a5-90c0-4048-8a79-aa974cf6a501</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[id='subscriptionTab']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
