<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Payment Information</name>
   <tag></tag>
   <elementGuidId>3672e270-22e3-4b1e-ba0e-10e96dd2253a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//p[@id='subtext'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;NJ Transit Receipt&quot;i >> internal:text=&quot;Payment Information&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>224f6471-4d39-4ba0-aa67-387ded33cddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-body1 css-1c9ngfa</value>
      <webElementGuid>ff3d8561-3537-4633-b3e3-b3bea68c8a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subtext</value>
      <webElementGuid>0824b667-9c4b-4c78-b452-cda329f5125f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Payment Information</value>
      <webElementGuid>22ca0c25-d3eb-4d24-a0bb-ec16bc978e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;printReceiptModal&quot;)/div[@class=&quot;MuiDialog-container MuiDialog-scrollPaper css-ekeie0&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation24 MuiDialog-paper MuiDialog-paperScrollPaper MuiDialog-paperWidthMd MuiDialog-paperFullWidth css-cwpu7v&quot;]/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;MuiDialogContent-root css-1ty026z&quot;]/p[@class=&quot;MuiTypography-root MuiDialogContentText-root MuiTypography-body1 MuiDialogContentText-root css-1wvkpe0&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-2 css-hezj9&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-sm-6 css-rpybyc&quot;]/p[@id=&quot;subtext&quot;]</value>
      <webElementGuid>b1798aa6-059f-4011-a72f-d6d63b5e1ab1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//p[@id='subtext'])[2]</value>
      <webElementGuid>80d88648-842f-4796-9ed7-84fb6d3baa15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='printReceiptModal']/div[3]/div/div/div[2]/p/div/div[2]/p</value>
      <webElementGuid>e7a5497a-7af8-47e2-bfc0-7af232d1ad9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$8.50'])[2]/following::p[1]</value>
      <webElementGuid>ad7f9518-336e-4e50-af0c-f3e406aedeef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Amount:'])[1]/following::p[1]</value>
      <webElementGuid>566a33e6-3c1b-40dc-9fe0-27cd172c1a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Receipt Number:'])[1]/preceding::p[1]</value>
      <webElementGuid>77d18ba4-c26a-4a18-b82f-d1a83c3d6692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Number:'])[1]/preceding::p[1]</value>
      <webElementGuid>15eb7b07-7c6c-49b2-afb2-c1f730a4cb76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/div/div[2]/p</value>
      <webElementGuid>06409624-1cfc-4d73-ace1-050c621ee2a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'subtext' and (text() = 'Payment Information' or . = 'Payment Information')]</value>
      <webElementGuid>109d8082-7c4b-403e-b3b3-7a6ac3bb082b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
