<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TransactionDate</name>
   <tag></tag>
   <elementGuidId>a4afda84-5c71-4d2e-8918-a85ec879861b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='transactionDateTxt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#transactionDateTxt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;NJ Transit Receipt&quot;i >> internal:text=&quot;11/26/2024 15:11:46&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4ca99e5b-7373-48e9-9236-49bc88e0ad5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-subText css-1c09nwh</value>
      <webElementGuid>0100fad1-8d4e-41e7-a753-6ccb79ba4da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transactionDateTxt</value>
      <webElementGuid>34f319e5-9969-4f0b-abf8-bccfc5bf7318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>11/26/2024 15:11:46</value>
      <webElementGuid>2993909d-b14d-40ed-8066-6721f524e3d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transactionDateTxt&quot;)</value>
      <webElementGuid>e3a6451e-9b4e-4c8b-8c7d-0c3b49fbaf75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='transactionDateTxt']</value>
      <webElementGuid>140cb2fd-5704-4af9-9870-43ffe5903863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='printReceiptModal']/div[3]/div/div/div[2]/p/div/div/div/div[2]/span[3]</value>
      <webElementGuid>38362f7d-392a-45ca-92bb-bf2dc4a98a37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Amount:'])[1]/following::span[3]</value>
      <webElementGuid>696a93e6-efa7-4614-b2cc-8f6a9962a950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Date:'])[1]/following::span[4]</value>
      <webElementGuid>56a216f4-885a-44f5-bb0e-c5d8deda01a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$8.50'])[3]/preceding::span[1]</value>
      <webElementGuid>a56c4687-7f71-40f4-9cc1-050e13d214fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Receipt Number:'])[1]/preceding::span[2]</value>
      <webElementGuid>19814473-ea2b-470b-b163-52331f84c9a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span[3]</value>
      <webElementGuid>d8a14f3c-b856-46dd-a227-016aabdcf364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'transactionDateTxt' and (text() = '11/26/2024 15:11:46' or . = '11/26/2024 15:11:46')]</value>
      <webElementGuid>18abec48-f307-4c11-83ce-08b0454da416</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
