<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_CardAccId</name>
   <tag></tag>
   <elementGuidId>a3244d31-840e-445d-bc5a-d7f316a6eae1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cardAccIdTxt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cardAccIdTxt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;NJ Transit Receipt&quot;i >> internal:text=&quot;0BEE741Q&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fbcfd9e6-a106-426c-b0bf-710905374681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-subText css-1c09nwh</value>
      <webElementGuid>259d48e8-2c3c-4c5d-840b-833e3eda7a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cardAccIdTxt</value>
      <webElementGuid>11a95b1b-89c3-4241-84e6-f9bb509160bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0BEE741Q</value>
      <webElementGuid>9bc366ce-adbd-4d98-a2ca-75fdf9901190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cardAccIdTxt&quot;)</value>
      <webElementGuid>b25f71af-637d-4370-991c-4622e85d2652</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='cardAccIdTxt']</value>
      <webElementGuid>3cc49148-46c5-4987-82d9-bf1841e3c713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='printReceiptModal']/div[3]/div/div/div[2]/p/div/div/div/div[2]/span[2]</value>
      <webElementGuid>d7be46b8-99c9-4c03-87e2-5df79c8a2a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Amount:'])[1]/following::span[2]</value>
      <webElementGuid>7dcbb246-07f4-4b78-9a3a-9ec3de75bdd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Date:'])[1]/following::span[3]</value>
      <webElementGuid>14d85648-c588-4fd9-aa37-ae38464a3ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$8.50'])[3]/preceding::span[2]</value>
      <webElementGuid>5dd53323-c804-49dc-9137-fc0ec9bdcab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Receipt Number:'])[1]/preceding::span[3]</value>
      <webElementGuid>a28f339f-78c6-4962-b6de-c97e72fcbe09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span[2]</value>
      <webElementGuid>2b35b24a-e38c-4c9a-b52f-4e2a294eea0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'cardAccIdTxt' and (text() = '0BEE741Q' or . = '0BEE741Q')]</value>
      <webElementGuid>7b0639a1-1955-4a9c-a36a-44cdad6095c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
