<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_8.50</name>
   <tag></tag>
   <elementGuidId>e6907bcd-ccf0-4504-a5db-c5cc84f996a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='amountTxt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#amountTxt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;NJ Transit Receipt&quot;i >> internal:text=&quot;$8.50&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>adaaae47-679b-40a6-a4f3-74d2ef8dc3e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-subText css-1c09nwh</value>
      <webElementGuid>49ec52e1-8380-4aaa-9cd1-8936169ac97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>amountTxt</value>
      <webElementGuid>3a2ae668-93d7-40db-9298-c850fca00bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$8.50</value>
      <webElementGuid>62304c0b-a9b0-498a-8277-65e65e5b15ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amountTxt&quot;)</value>
      <webElementGuid>6e3032ef-1959-436e-969a-01968c765297</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='amountTxt']</value>
      <webElementGuid>f2805128-42b2-47cb-9b60-3d7b0a848e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='printReceiptModal']/div[3]/div/div/div[2]/p/div/div/div/div[2]/span[4]</value>
      <webElementGuid>60faa9a1-47f9-4304-95da-d8c1175fda12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Amount:'])[1]/following::span[4]</value>
      <webElementGuid>cb73f151-9be6-4141-902e-fb0f4bf497e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Date:'])[1]/following::span[5]</value>
      <webElementGuid>a611d4cb-ae8b-49ac-9e8c-593ebf915f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Receipt Number:'])[1]/preceding::span[1]</value>
      <webElementGuid>06ab1dd5-aba6-4093-b1f2-b9f8977424ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Number:'])[1]/preceding::span[2]</value>
      <webElementGuid>d7e36206-fceb-4197-9b8c-1af970272dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span[4]</value>
      <webElementGuid>73113840-88e2-449d-8b91-21bec9c1109e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'amountTxt' and (text() = '$8.50' or . = '$8.50')]</value>
      <webElementGuid>906da284-7115-45da-9ceb-d4be750e958e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
