<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>refundAmountText</name>
   <tag></tag>
   <elementGuidId>9b458dc9-a1f0-43f5-847a-e276fbd4743b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>((//tbody//tr)[11]//th)[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
