<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_FARE-PAY Card Number is too short</name>
   <tag></tag>
   <elementGuidId>2f2fd54d-0b0c-4717-a76a-940e1106e71c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='serialNumber-error-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#serialNumber-error-text</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'serialNumber-error-text' and (text() = 'FARE-PAY Card Number is too short' or . = 'FARE-PAY Card Number is too short')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;FARE-PAY Card Number is too short&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>70368bea-03dd-41cc-8c65-20235c59d0d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeSmall MuiFormHelperText-contained MuiFormHelperText-filled css-18emikf</value>
      <webElementGuid>1cb90777-681f-4d5f-adb3-2e291c2bc667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>serialNumber-error-text</value>
      <webElementGuid>69406fc0-d0b2-4d48-b94f-39dcbdf8430e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>10d4f0ee-53e3-430c-99f9-018657bef20a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FARE-PAY Card Number is too short</value>
      <webElementGuid>574c4a03-1ec1-4b8b-9ec7-6b901fff4d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serialNumber-error-text&quot;)</value>
      <webElementGuid>9a4e456f-8d89-4f7f-97b2-09d745d0545f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='serialNumber-error-text']</value>
      <webElementGuid>e57cdb17-097f-4031-a77f-353396fd316a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='farepayCardForm']/div[3]/div/div/div/div[2]/p</value>
      <webElementGuid>aa702341-9446-4fed-8fab-3b62f80695f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::p[1]</value>
      <webElementGuid>1c450fbc-fd56-4b64-8dfa-a54d6ce09255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FARE-PAY Card Number'])[1]/following::p[1]</value>
      <webElementGuid>51caa4e3-c2f0-427e-b8cf-6c2551d2fc98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PIN'])[1]/preceding::p[1]</value>
      <webElementGuid>dfebf1eb-dc0f-44e9-8c34-1d154c4dcb45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[2]/preceding::p[1]</value>
      <webElementGuid>8e7182de-96ee-411a-9d88-ef5e7be966a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FARE-PAY Card Number is too short']/parent::*</value>
      <webElementGuid>82c8e055-d5f1-42c0-8559-f59954cd5004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>9f8fb0f1-7b9b-4a64-b86b-10e7464687fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'serialNumber-error-text' and (text() = 'FARE-PAY Card Number is too short' or . = 'FARE-PAY Card Number is too short')]</value>
      <webElementGuid>b108603f-959b-4048-bac7-5a9ca242eb21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
