<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Card Number_visaCard</name>
   <tag></tag>
   <elementGuidId>f249e3c3-28e0-4508-aed9-0f1e1458c498</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='visaCard']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#visaCard</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'visaCard' and @alt = 'visa card' and @src = '/njt-web/static/media/visa_card.d6157c0bb3472d9c1c7b.png']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;visa card&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>19198c26-f864-4b2d-be17-bb7baa77874d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-hq5bof</value>
      <webElementGuid>e8526934-7924-4ef1-9799-3cc0a0327ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visaCard</value>
      <webElementGuid>30efea06-328c-4c65-b63b-1aaf718c26c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>visa card</value>
      <webElementGuid>f7a9f20d-b298-4bf0-bdc6-afc60452c271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/njt-web/static/media/visa_card.d6157c0bb3472d9c1c7b.png</value>
      <webElementGuid>22cc8a2f-4a54-4da8-b397-e1e690eb8fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visaCard&quot;)</value>
      <webElementGuid>5fdabbfa-beef-457a-881f-0d932ea068a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='visaCard']</value>
      <webElementGuid>b6c0923d-9522-4aac-9b8e-e8720ba7342c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='cardRegistrationForm']/div/div/div/div/div/div/div/div/img</value>
      <webElementGuid>58a3764e-3b37-474d-98ae-6b9cc8f50249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='visa card']</value>
      <webElementGuid>c01fcb41-6cc9-45e2-9f63-12c41abc44af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/img</value>
      <webElementGuid>9f396761-736b-48d3-8da8-af9ed12d796e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'visaCard' and @alt = 'visa card' and @src = '/njt-web/static/media/visa_card.d6157c0bb3472d9c1c7b.png']</value>
      <webElementGuid>cc71d6f8-3004-42de-8580-87024e966f42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
