<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Card Number_masterCard</name>
   <tag></tag>
   <elementGuidId>21a49bfc-51a6-4f34-8cea-49bed536135f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='masterCard']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#masterCard</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Master card&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2ee1a209-d21d-41cd-9208-7fd73338dda2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-9rucl0</value>
      <webElementGuid>5c64d62e-cc6a-4926-ae2f-e05969ec3fc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>masterCard</value>
      <webElementGuid>b9e9ea33-581a-4e98-a0d5-33899e4b019b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Master card</value>
      <webElementGuid>0c4c037e-bcdb-403c-ba88-68c4f53da29f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/njt-web/static/media/master_card.7c6c3e9c8972a5588468.png</value>
      <webElementGuid>ca1802b1-7f5e-4e77-92d2-faa76a3b1779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;masterCard&quot;)</value>
      <webElementGuid>8de7d48f-663e-44d5-a41a-f53a0c03cb4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='masterCard']</value>
      <webElementGuid>bb7637ad-a06c-4878-8ffe-81cd269b0399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='cardRegistrationForm']/div/div/div/div/div/div/div/div/img[2]</value>
      <webElementGuid>34bf155b-89a2-4e39-a1a6-93e465c784a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Master card']</value>
      <webElementGuid>3adc4018-d267-41c1-912a-165d46926b6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>a994c6d7-d4a3-4ae0-9719-5d0e22a09427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'masterCard' and @alt = 'Master card' and @src = '/njt-web/static/media/master_card.7c6c3e9c8972a5588468.png']</value>
      <webElementGuid>a523a5c7-cf35-4766-86ee-c3e5fd18165a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
