<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Card Number_jcbCard</name>
   <tag></tag>
   <elementGuidId>8f8cc975-64c7-4b59-ae9b-c6a6333204d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='jcbCard']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jcbCard</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Jcb card&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6d2a916c-0e75-4efa-9af9-bb0898e33076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-agf9n2</value>
      <webElementGuid>91ffab09-6434-41f3-b153-c22b71af6b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jcbCard</value>
      <webElementGuid>2de9711a-3de1-44e5-9d99-ac011b7ecea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Jcb card</value>
      <webElementGuid>9794218c-3b0e-4401-a291-f4a9b9912789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/njt-web/static/media/jcb_card.f4a8ae47c67ad03ce105.png</value>
      <webElementGuid>71ca9422-2374-4ee4-8b7f-929299ea3744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jcbCard&quot;)</value>
      <webElementGuid>777e1772-72bb-4939-8157-aea9423ae876</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='jcbCard']</value>
      <webElementGuid>d4e9d665-55a0-437a-b5af-9b4ce1332781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='cardRegistrationForm']/div/div/div/div/div/div/div/div/img[5]</value>
      <webElementGuid>6c8c0157-43bf-4716-9496-063639e559ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Jcb card']</value>
      <webElementGuid>40fc109c-9d01-444b-abf1-2b51fb6160d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[5]</value>
      <webElementGuid>b2774dd8-dde0-46d7-aa54-b3b56c5be217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'jcbCard' and @alt = 'Jcb card' and @src = '/njt-web/static/media/jcb_card.f4a8ae47c67ad03ce105.png']</value>
      <webElementGuid>a22c268e-ccb1-4ae4-bc1f-60d015b5c40e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
