<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Please enter your credit card information below</name>
   <tag></tag>
   <elementGuidId>d75ab5e8-0360-4630-a419-11cc48929de1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiCardContent-root.css-1qw96cp > div.MuiBox-root.css-0 > #title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Please enter your credit card information below. This information will be used t&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ac167968-b4d4-48a5-a2e6-641c2905a491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-desc css-1t2r6k0</value>
      <webElementGuid>439c4eec-83e7-4496-ad7f-c3c1d094d6d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>02df39a8-adec-40a7-ae89-fcb8e2082f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter your credit card information below. This information will be used to look up your transactions.</value>
      <webElementGuid>7d89ed2c-8615-4016-937f-7d9322892b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentTabsCard&quot;)/div[@class=&quot;MuiCardContent-root css-1qw96cp&quot;]/div[@class=&quot;MuiBox-root css-0&quot;]/span[@id=&quot;title&quot;]</value>
      <webElementGuid>9bf3a57e-c9fe-432d-ad43-244fe3c74925</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='title']</value>
      <webElementGuid>2d16adce-ae17-403c-9491-a90668b5b9c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paymentTabsCard']/div/div[4]/span</value>
      <webElementGuid>d215e3bd-b0a8-410a-b655-29b8ad4ad77b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::span[1]</value>
      <webElementGuid>81a501d5-58f2-4927-92e2-82fc9f69d2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Number'])[1]/preceding::span[1]</value>
      <webElementGuid>bfdae78b-2e8a-4014-ace7-8f8b66454f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/preceding::span[3]</value>
      <webElementGuid>4df897cf-846b-4753-a985-2829f1e650e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please enter your credit card information below. This information will be used to look up your transactions.']/parent::*</value>
      <webElementGuid>91ec669a-c30a-48ba-ad42-7b91a1f44f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span</value>
      <webElementGuid>68e44e5c-0225-45fe-992f-da2796ccd930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'title' and (text() = 'Please enter your credit card information below. This information will be used to look up your transactions.' or . = 'Please enter your credit card information below. This information will be used to look up your transactions.')]</value>
      <webElementGuid>620165de-9469-4d8b-b491-779be2b89e6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
