<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Bus (1)</name>
   <tag></tag>
   <elementGuidId>97870047-92b2-4c7a-9cb1-82a1545db4df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Step1BuyTicketsBusTab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='Step1BuyTicketsBusTab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Bus&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7e0b9141-20af-4c40-b14b-18ea364cf338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiTab-root MuiTab-labelIcon MuiTab-textColorSecondary css-1wuduij</value>
      <webElementGuid>6436fd0d-448f-41e2-b53e-e1a54088d1cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4ec5823d-e4b0-47ec-b8be-edd437df2b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>74057d64-2f0a-4668-864c-54eb0730a26a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>8c019ae0-4344-424b-90d5-93432c2f2e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c9691961-e76d-44e5-afb2-c29cb84198b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Step1BuyTicketsBusTab</value>
      <webElementGuid>f6cee115-cf89-4854-8860-97858dbc339a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bus</value>
      <webElementGuid>0a3c28b8-7fb4-4192-85b2-2d1e44ed425d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Step1BuyTicketsBusTab&quot;)</value>
      <webElementGuid>2af6440a-cfa8-417f-916a-2d2598641c8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='Step1BuyTicketsBusTab']</value>
      <webElementGuid>8c8f1dc2-4ec0-480c-8c1b-ce9e0ebcaad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='transitTypes']/div/div/button[2]</value>
      <webElementGuid>cc766fab-aa22-4bf3-b500-47740f9af1c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rail'])[1]/following::button[1]</value>
      <webElementGuid>d837e3ed-8163-49e0-af7b-8581833d1078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy Tickets'])[2]/following::button[3]</value>
      <webElementGuid>7e628ac3-800b-4291-acc4-67f9ff20ed68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Light Rail'])[1]/preceding::button[1]</value>
      <webElementGuid>64d8bce1-a924-4ff8-871d-d77e1de22d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bus']/parent::*</value>
      <webElementGuid>d4595159-a22e-483a-94c8-8d129cffe68e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button[2]</value>
      <webElementGuid>d9d28a4f-7988-4749-9821-6b1cef68e845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'Step1BuyTicketsBusTab' and (text() = 'Bus' or . = 'Bus')]</value>
      <webElementGuid>d28589f4-0a8b-4bfc-9387-7558eb131cf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
