<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_13-Broad Street - Clinton Avenue</name>
   <tag></tag>
   <elementGuidId>8fb2d19b-70ec-455c-acaf-a4f0725753ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#route-option-8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='route-option-8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;13-Broad Street - Clinton Avenue&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2d0e30a3-ba51-4915-bc7f-e8eb55f5db51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f867279a-e29e-4428-9439-c1ec700365a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>3844f919-903d-425e-a26c-1ea5dd12cc1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>route-option-8</value>
      <webElementGuid>88a78e86-4f4f-4a2c-800c-880b94b0e173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>44dcfe5a-8f44-4c92-ad3e-febbaba50877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>475576d7-836e-4082-8177-838ef9ca30ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>16f8a55b-ec3e-45ad-af3d-eb5524a192b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option Mui-focused</value>
      <webElementGuid>c60e2ad6-d931-4870-8336-38b633db8602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>13-Broad Street - Clinton Avenue </value>
      <webElementGuid>1d278ddf-8740-4db6-9fb1-17d68a1b1996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;route-option-8&quot;)</value>
      <webElementGuid>d965ea19-18ac-4719-bf0a-75ea1311b892</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='route-option-8']</value>
      <webElementGuid>28aab13c-fc6c-4821-ba9e-ae98a2001f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='route-listbox']/li[9]</value>
      <webElementGuid>27a12b71-5c05-4da8-90c9-113ba61f7636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[1]/following::li[9]</value>
      <webElementGuid>3671f0cb-e79e-4ae9-bf92-633f0188b10f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::li[9]</value>
      <webElementGuid>50987433-b99e-4803-8efe-f3af83cae513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='13-Broad Street - Clinton Avenue']/parent::*</value>
      <webElementGuid>0a21c10e-d0c6-4188-bfb5-a913bfaf6505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]</value>
      <webElementGuid>4da403e0-b239-417d-8afb-a90008e2c357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'route-option-8' and (text() = '13-Broad Street - Clinton Avenue ' or . = '13-Broad Street - Clinton Avenue ')]</value>
      <webElementGuid>3914a02e-1282-415c-8597-4e5859d2fab5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
