<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_23-North Bergen - Weehawken - Hoboken</name>
   <tag></tag>
   <elementGuidId>7cf94c23-18a0-4704-ac1f-ad5d03c3d1ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#route-option-12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='route-option-12']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;23-North Bergen - Weehawken - Hoboken&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>45d454bc-4772-46e0-9faa-81dc04626253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a40380df-8760-4adf-9250-f481da04d174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>5030679d-0edb-4aad-9d40-ab8c211f3df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>route-option-12</value>
      <webElementGuid>e45830f3-d9de-4bfe-879c-2ca8c8340ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>deae046a-21cc-4dc5-94eb-b2c73b148c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>75a1e051-b9cb-462a-a2fd-a1a30b71802f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8f0136b1-b69f-47d6-abb1-e13d81b5ce62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option Mui-focused</value>
      <webElementGuid>1ce4f579-18d8-40fc-9c2f-4cb071efd474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>23-North Bergen - Weehawken - Hoboken</value>
      <webElementGuid>cd2716ce-cfcc-4c00-ad86-87adc5ecae74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;route-option-12&quot;)</value>
      <webElementGuid>0bfcde1c-82c1-4c06-aba2-1b3505bf1519</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='route-option-12']</value>
      <webElementGuid>c443bf53-9531-421a-8e57-656756d4b1c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='route-listbox']/li[13]</value>
      <webElementGuid>97b4a359-0f6f-45b6-99b6-cb6d4ed6ae70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[1]/following::li[13]</value>
      <webElementGuid>61b8ec43-e7e9-48ea-b6b4-a5260004d174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::li[13]</value>
      <webElementGuid>0e333410-baf8-4c21-8ecf-a425f4b7f181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='23-North Bergen - Weehawken - Hoboken']/parent::*</value>
      <webElementGuid>ab9dd2fe-fa1a-4fd4-aa8a-c80c2f2e124e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[13]</value>
      <webElementGuid>a07447c8-d350-4962-af87-d693868e9a29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'route-option-12' and (text() = '23-North Bergen - Weehawken - Hoboken' or . = '23-North Bergen - Weehawken - Hoboken')]</value>
      <webElementGuid>a4ae35df-1381-4e03-8aac-b3607f4f9c66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
