<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_6-Ocean Avenue - Journal Square</name>
   <tag></tag>
   <elementGuidId>1a32cd5e-b368-4e78-828a-7e7e90a8d58a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#route-option-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='route-option-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;6-Ocean Avenue - Journal Square&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>3f5d45ea-ad6d-4995-aada-29ed34619c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2ef52f20-0f5c-496e-a52e-a57807516b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>86ac8c71-cb61-489b-ba9d-22a775284f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>route-option-3</value>
      <webElementGuid>c237dd71-799d-4efa-869c-9aeccf4637db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>48f7fea9-e4b3-4955-b573-760b049c1719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3a9ae768-dae6-4bc2-b79f-9633a149976f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4679b9fd-4ab9-4866-9c9a-103f6d47e1c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option Mui-focused</value>
      <webElementGuid>59205421-edaf-4dff-9c17-a242d0f5c9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>6-Ocean Avenue - Journal Square</value>
      <webElementGuid>9d0df013-f34b-40bb-9cc8-ef2794d08f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;route-option-3&quot;)</value>
      <webElementGuid>edea1544-4f3f-49a3-a983-0db0b153d9bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='route-option-3']</value>
      <webElementGuid>790af1f7-f9d6-4e54-846f-828349a5a0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='route-listbox']/li[4]</value>
      <webElementGuid>f56348de-e6a5-472a-b3d7-1dfc372535df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[1]/following::li[4]</value>
      <webElementGuid>f9fcf6e9-abea-4b9c-92e1-40fb4d082da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::li[4]</value>
      <webElementGuid>216e066f-d63d-4a77-a6c6-b5565b5b0841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='6-Ocean Avenue - Journal Square']/parent::*</value>
      <webElementGuid>ced0fb8a-dff9-4869-94a7-2dd436703069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/ul/li[4]</value>
      <webElementGuid>b2f4fdce-9105-4827-82c8-952641d251c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'route-option-3' and (text() = '6-Ocean Avenue - Journal Square' or . = '6-Ocean Avenue - Journal Square')]</value>
      <webElementGuid>c8bd902e-81df-414b-b2f9-2ca9c2147314</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
