<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Invalid Cardholders Name</name>
   <tag></tag>
   <elementGuidId>2998a6c7-9f64-4308-ac58-598b9e0c487e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ccHolderName-error-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='ccHolderName-error-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Invalid Cardholder's Name&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>7e5a5a1b-5a73-416c-b005-498cd119cae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeSmall MuiFormHelperText-contained MuiFormHelperText-filled css-18emikf</value>
      <webElementGuid>15a5bdee-8b4f-4c38-9151-8f31421df1ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ccHolderName-error-text</value>
      <webElementGuid>64c4edff-d2c5-428d-be92-1c08a120eb9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>8964a8b3-7c55-4fea-9e3a-b7a86183904c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid Cardholder's Name</value>
      <webElementGuid>6cb955cf-2b2b-42db-8d59-67f755b6ca3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ccHolderName-error-text&quot;)</value>
      <webElementGuid>6d38c567-07f4-4ded-b5b3-60fb0ee3c255</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='ccHolderName-error-text']</value>
      <webElementGuid>3d0ede7d-cda2-48d3-b76b-83d99efc7c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='patDebtForm']/div/div/div/div/div[2]/p</value>
      <webElementGuid>a615f691-4cd9-4f43-b488-9534c3a29604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[3]/following::p[1]</value>
      <webElementGuid>1f21e243-591a-424f-a7dc-418be61703fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Number'])[2]/preceding::p[1]</value>
      <webElementGuid>32a4e132-75de-4a15-967b-eae6fe36624e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[4]/preceding::p[1]</value>
      <webElementGuid>f3c00a71-9f0b-4950-a7a0-346f6680aae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/p</value>
      <webElementGuid>e69dc7c5-490d-4767-8735-e3164a3e03de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'ccHolderName-error-text' and (text() = concat(&quot;Invalid Cardholder&quot; , &quot;'&quot; , &quot;s Name&quot;) or . = concat(&quot;Invalid Cardholder&quot; , &quot;'&quot; , &quot;s Name&quot;))]</value>
      <webElementGuid>1dbe8d02-8875-4713-8e81-d2ed671792d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
