<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Maximum amount is 500</name>
   <tag></tag>
   <elementGuidId>6af9a0c0-4579-4f98-94f8-86f02c06fb77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='rechargeAmt-error-text']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Maximum amount is $500' or . = 'Maximum amount is $500')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rechargeAmt-error-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Maximum amount is $500&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>f6548d6d-b647-4bf5-98a5-dfd7df3e8b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeSmall MuiFormHelperText-contained MuiFormHelperText-filled css-18emikf</value>
      <webElementGuid>72197f26-fd0c-4b1e-ab41-1828ab8be912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rechargeAmt-error-text</value>
      <webElementGuid>d784a56b-2410-4fb5-a7ff-79fe3bdee73d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>17f8e63c-4a6c-45ae-b4f4-67e16c05c210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Maximum amount is $500</value>
      <webElementGuid>1f6db328-8689-4a6a-80df-33a06cb86358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rechargeAmt-error-text&quot;)</value>
      <webElementGuid>65000b6b-f657-44d9-ab14-ae5419ac493c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='rechargeAmt-error-text']</value>
      <webElementGuid>c6fab390-3485-4adf-a5b9-02d9a240e641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addFundsModal']/div[3]/div/div[2]/div[3]/fieldset/div/div/div/div[2]/p</value>
      <webElementGuid>8eb2df8b-8c9d-4db0-a0a3-afffb3fc0597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[3]/following::p[1]</value>
      <webElementGuid>7303a90e-2483-46fe-bc33-f679e6d1a21c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reload amount'])[1]/following::p[1]</value>
      <webElementGuid>01f8db11-bafe-4b5d-af4c-9f77e55d0b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$25'])[1]/preceding::p[1]</value>
      <webElementGuid>789d25eb-857f-4b6b-a27e-51209c44074e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$50'])[1]/preceding::p[1]</value>
      <webElementGuid>8827057d-1faa-4792-8c1a-ca354494d391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Maximum amount is $500']/parent::*</value>
      <webElementGuid>b34e89cd-4b9f-41ba-92a8-3a8499d35872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>c0f83772-6f74-44ca-a3d4-9c4293259c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'rechargeAmt-error-text' and (text() = 'Maximum amount is $500' or . = 'Maximum amount is $500')]</value>
      <webElementGuid>f60a5888-6fbe-4846-9d81-d92e1db065db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
