<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_fare_pay_cardNumber</name>
   <tag></tag>
   <elementGuidId>529f4dd1-3023-4b65-946d-e8f0d96788fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='6375-0041-0997-8888']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#6375-0041-0997-8888</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Selected Fare-Pay Card Information&quot;i >> internal:text=&quot;6375-0041-0997-8888&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4b384c25-e20a-4add-ab72-b2ae5e80f94b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-value css-13ygth7</value>
      <webElementGuid>17559dcb-c28a-4ba9-9371-e74bd800d4ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>6375-0041-0997-8888</value>
      <webElementGuid>2a0c9d0c-78b7-41c8-9931-57084d9d167b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>6375-0041-0997-8888</value>
      <webElementGuid>fa15443d-b38a-471a-bac3-a1ce0df22379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6375-0041-0997-8888&quot;)</value>
      <webElementGuid>4ac8f3a3-fcd3-4bdb-8599-b1aa7a958925</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='6375-0041-0997-8888']</value>
      <webElementGuid>0f41ac57-40dc-4d70-8279-cfd075db3281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboardCard']/div/div/div/div/div/table/tbody/tr/td[2]/span</value>
      <webElementGuid>cbf2b601-3e4b-4723-823b-d0bcbc6f1d0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Number'])[1]/following::span[1]</value>
      <webElementGuid>1718689a-3993-4b37-bf5a-fe1835c10d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::span[2]</value>
      <webElementGuid>0941f0f4-5a90-4907-b587-22eb95b4445f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Status'])[1]/preceding::span[1]</value>
      <webElementGuid>ea782397-939d-47c6-9aea-ddf08721c098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/preceding::span[2]</value>
      <webElementGuid>7c6b755a-4df5-48ba-9e4c-f9e6b9079890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/span</value>
      <webElementGuid>3638928a-335e-4f16-bfe5-41932e31c0c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '6375-0041-0997-8888' and (text() = '6375-0041-0997-8888' or . = '6375-0041-0997-8888')]</value>
      <webElementGuid>72fb50a0-6b1d-4969-8feb-4c8a8d99c42d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
