<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Note NJ TRANSIT will automatically reload a monthly pass to your FARE-PAY card account by last day of this month</name>
   <tag></tag>
   <elementGuidId>5bd52836-20ac-4fb5-8f45-3d27529b3bfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ticketsNote</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ticketsNote']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Note: NJ TRANSIT will automatically reload a monthly pass to your FARE-PAY card &quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f14f356f-45c0-4465-9832-29db1f6ae143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-desc css-1amlqwo</value>
      <webElementGuid>0fbbadf4-e529-49ee-a71f-cfc99c1e589b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ticketsNote</value>
      <webElementGuid>9e526480-d18c-440c-972c-558e1897eddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Note: NJ TRANSIT will automatically reload a monthly pass to your FARE-PAY card account by last day of this month.</value>
      <webElementGuid>fa122153-f00f-4aba-a7f3-e904fd6de9be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ticketsNote&quot;)</value>
      <webElementGuid>4f913638-277f-4e4e-bd94-0619e82850ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ticketsNote']</value>
      <webElementGuid>3a6322fb-e2fa-4a24-9e85-b1d0656ea791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ticketsNote' and (text() = 'Note: NJ TRANSIT will automatically reload a monthly pass to your FARE-PAY card account by last day of this month.' or . = 'Note: NJ TRANSIT will automatically reload a monthly pass to your FARE-PAY card account by last day of this month.')]</value>
      <webElementGuid>50ea5aba-da39-4d5a-ab6b-e5fae51f52e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addFundsModal']/div[3]/div/div[2]/div[4]/div/div/div[2]/span</value>
      <webElementGuid>5b3ed32a-bb1a-42e7-b85c-03f63ecda785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/span</value>
      <webElementGuid>240d1895-b10f-498e-ba3e-213f5669bbc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Plan'])[1]/following::span[1]</value>
      <webElementGuid>9ec854d4-41de-47f7-a342-b07003cc7ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Methods'])[1]/preceding::span[1]</value>
      <webElementGuid>fd077af2-2996-4012-babd-8fc22f781338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Note:']/parent::*</value>
      <webElementGuid>4c25351a-2692-456b-bbc5-b3cd7d8fa4bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
