<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_tripAmount</name>
   <tag></tag>
   <elementGuidId>43220170-4676-45fd-93ef-f7fb70004a60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='transactionRow-0']/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.MuiTableCell-root.MuiTableCell-body.MuiTableCell-sizeSmall.css-1dqu9ge</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;$25.50&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>a8496874-0c2c-4b4b-b0cf-6bb01d890a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTableCell-root MuiTableCell-body MuiTableCell-sizeSmall css-1dqu9ge</value>
      <webElementGuid>55e10c6d-36ae-4d97-9fc4-0907e5fc9971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$25.50</value>
      <webElementGuid>29953795-210b-4790-8d46-5fd542da5bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transactionRow-0&quot;)/td[@class=&quot;MuiTableCell-root MuiTableCell-body MuiTableCell-sizeSmall css-1dqu9ge&quot;]</value>
      <webElementGuid>06172e7d-7977-4f56-85e5-f90cae64cc89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='transactionRow-0']/td[3]</value>
      <webElementGuid>68fbe328-19df-4cb7-8f10-e83cd120fcc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fare'])[1]/following::td[3]</value>
      <webElementGuid>46279179-293e-49ed-8b8e-c8f59c4cc2ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ticket Description'])[1]/following::td[3]</value>
      <webElementGuid>c3f48b4a-e7d4-4b84-8c0c-618357794d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$60.00'])[1]/preceding::td[3]</value>
      <webElementGuid>a3127b08-1b1a-4b50-9b27-d1aa629452f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$25.50']/parent::*</value>
      <webElementGuid>95738d19-2d18-49ba-8bd1-39f1771962b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>88f00547-ec1a-4a9a-9bb9-15c31284d914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '$25.50' or . = '$25.50')]</value>
      <webElementGuid>530ab4e1-3f35-46af-9e6a-0521ac2fc2ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
