<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_total_fp_refund_amount</name>
   <tag></tag>
   <elementGuidId>5d4eae1b-724e-44e0-8bef-f89f3f000d3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//th[@id='price'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>table.MuiTable-root.css-n3lbqt > thead.MuiTableHead-root.css-1ngqdxa > tr.MuiTableRow-root.MuiTableRow-head.css-1jq8fg > #price</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=columnheader[name=&quot;$25.50&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>9a7868b9-9a93-4964-9af8-ceda79ba8119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTableCell-root MuiTableCell-head MuiTableCell-sizeSmall css-a54omf</value>
      <webElementGuid>e98d1981-1bae-4980-943c-cf1a5dc80026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>3021a7c4-27d4-4c30-95ab-33d9afb0a913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>15%</value>
      <webElementGuid>b21ef7ee-5719-4846-8512-f28faa24e409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>price</value>
      <webElementGuid>c595dca5-6603-4bf5-b1d7-d00a91a18660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$25.50</value>
      <webElementGuid>f6d2f98b-9a00-4207-b0b4-4a523721ffb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;historyModal&quot;)/div[@class=&quot;MuiDialog-container MuiDialog-scrollPaper css-ekeie0&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation24 MuiDialog-paper MuiDialog-paperScrollPaper MuiDialog-paperWidthMd MuiDialog-paperFullWidth css-cwpu7v&quot;]/div[@class=&quot;MuiDialogContent-root css-69br6q&quot;]/div[@class=&quot;MuiBox-root css-1r12575&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-2 css-1yatug&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-sm-8 MuiGrid-grid-md-8 MuiGrid-grid-lg-8 css-1iqiv84&quot;]/div[@class=&quot;MuiBox-root css-1ebnygn&quot;]/div[@class=&quot;MuiTableContainer-root css-kge0eu&quot;]/div[@class=&quot;MuiBox-root css-1m97wo8&quot;]/table[@class=&quot;MuiTable-root css-n3lbqt&quot;]/thead[@class=&quot;MuiTableHead-root css-1ngqdxa&quot;]/tr[@class=&quot;MuiTableRow-root MuiTableRow-head css-1jq8fg&quot;]/th[@id=&quot;price&quot;]</value>
      <webElementGuid>a8e62aaa-92b2-4170-89b2-8789013cf672</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//th[@id='price'])[2]</value>
      <webElementGuid>fcd358a5-89e3-4207-a4e8-8e71df25050f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[@id = 'price' and (text() = '$25.50' or . = '$25.50')]</value>
      <webElementGuid>821fe17e-3267-48c3-ad05-be719992440b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='historyModal']/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div[2]/table/thead/tr/th[2]</value>
      <webElementGuid>5aadb0de-11be-484e-bddd-c5dbc16b0337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/thead/tr/th[2]</value>
      <webElementGuid>baa439ee-4b64-46eb-9b12-f76fdc4c1924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$80.00'])[1]/following::th[2]</value>
      <webElementGuid>eaf749e5-2f21-447b-a552-43ffd76dd111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/preceding::th[1]</value>
      <webElementGuid>d224d5e1-ae84-4dfd-b739-7c136c4579b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proceed To Checkout'])[1]/preceding::th[1]</value>
      <webElementGuid>9318dc36-09d2-47ba-9460-fdcfaf8bf621</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
