<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>eddd24bb-ce8a-4de9-ac17-843c7c6fc026</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>body > div:nth-of-type(2) > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(5) > div >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a8b49efe-ef4b-4857-a344-e6f13ce6be18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[2]/div[1]</value>
      <webElementGuid>ef8d1d75-eb03-4fec-8875-dcacf5807c89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>ffbd1db1-5260-4a4c-a71b-dbeced699bb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
