<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Account LoginUser NamePasswordLoginRem_be181f</name>
   <tag></tag>
   <elementGuidId>76260d7b-c00e-4aeb-8ade-308715cc58dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginForm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='loginForm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Account LoginUser NamePasswordLoginRemember me Forgot Password?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>a0569542-ba41-43ae-91c6-50412e2cfc04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-jf85is</value>
      <webElementGuid>23320bab-154c-4366-94f4-d34db207c391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginForm</value>
      <webElementGuid>dce130b6-e73f-4bea-ac57-a5f5c12f6177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>79190520-c737-4b30-b521-e281fb1f49dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Account LoginUser Name​Password​LoginRemember me Forgot Password?</value>
      <webElementGuid>4bd5f971-beba-4117-9863-606fe1cd91d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginForm&quot;)</value>
      <webElementGuid>0cef0a9a-3f2e-435b-8e56-625e49ad417b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@id='loginForm']</value>
      <webElementGuid>3de4157c-3cd4-4d47-9bc9-c5102c0c6a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/form</value>
      <webElementGuid>c29038cb-f60e-4162-9c13-85e2ac0ebcfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>f86a58d9-45a1-4212-ad7c-35c84c1c5dda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[@id = 'loginForm' and (text() = 'Account LoginUser Name​Password​LoginRemember me Forgot Password?' or . = 'Account LoginUser Name​Password​LoginRemember me Forgot Password?')]</value>
      <webElementGuid>9e09b1ea-f920-4633-ad6b-23bacd79b165</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
