<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__a-qayye628vmwn</name>
   <tag></tag>
   <elementGuidId>080d9ef5-e19c-4c3d-9df9-a872bca859c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-qayye628vmwn&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-qayye628vmwn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;a-qayye628vmwn&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f7f49230-4aa7-454b-a61b-bcb9bf7e5220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>53f7fbb7-1698-48ba-b451-7b9d2ac0757e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>d833ed14-cb3b-4882-a885-730860e2392d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>bed568ed-d7b3-4ada-b853-c990aebba55a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>c2d06389-a7a1-4f9f-9478-bd4401851972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-qayye628vmwn</value>
      <webElementGuid>2c935be0-967a-433f-b2b5-e3aaa5bf5502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7bc1fabf-3661-4beb-b6a5-ced4aea587d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>7eadb1b8-8dc0-44e2-8459-20033fc650c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>ea900971-8717-4f4f-bec2-b1ba931e09c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdnPXgUAAAAALUJNuOkSW9A2ZpPokOfuo6fzFLq&amp;co=aHR0cHM6Ly9jbXNxYS5jbXNzZXJ2aWNlcy51czo0NDM.&amp;hl=en&amp;type=image&amp;v=I0bG74fWAenNf3Z5ncHSz-bd&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=8jzves2t00v6</value>
      <webElementGuid>d72d4327-a11e-4126-83ed-3c29c376732c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_captcha&quot;)/div[1]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>2022b413-62d0-425a-b527-6d969f2965aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-qayye628vmwn']</value>
      <webElementGuid>3854e898-bfad-4d10-aff8-c74d7ce43104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login_captcha']/div/div/div/iframe</value>
      <webElementGuid>0be3b21f-933c-4679-99e1-2dda1ccc20db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>2d91187d-f726-458d-97b2-f0fc6cc87e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-qayye628vmwn' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdnPXgUAAAAALUJNuOkSW9A2ZpPokOfuo6fzFLq&amp;co=aHR0cHM6Ly9jbXNxYS5jbXNzZXJ2aWNlcy51czo0NDM.&amp;hl=en&amp;type=image&amp;v=I0bG74fWAenNf3Z5ncHSz-bd&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=8jzves2t00v6']</value>
      <webElementGuid>ce723932-e29b-478a-903f-e83e5fb2e5ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
