<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SeniorDisabled</name>
   <tag></tag>
   <elementGuidId>c1e18662-1d13-48bb-aa3f-8b29495ca887</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='addFarepayCard']/div/div/div[7]/div/div[2]/div/div/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Senior/Disabled​' or . = 'Senior/Disabled​')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.MuiInputBase-formControl.MuiInputBase-sizeSmall.css-nyy6b6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.MuiInputBase-root</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5ccca42f-58a2-425f-b49c-62de9e5c278a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary MuiInputBase-formControl MuiInputBase-sizeSmall css-nyy6b6</value>
      <webElementGuid>f1dd3fce-f447-4156-b13c-1d2dde1cc04d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Senior/Disabled​</value>
      <webElementGuid>b9f2ff85-9d8e-47c2-b8b1-45447cdb9506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addFarepayCard&quot;)/div[@class=&quot;MuiCardContent-root css-1qw96cp&quot;]/div[@class=&quot;main-card-border-custom MuiBox-root css-gajhq5&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiCard-root css-s18byi&quot;]/div[@class=&quot;MuiCardContent-root css-13bdn6&quot;]/div[@class=&quot;MuiBox-root css-11ze7cv&quot;]/div[@class=&quot;MuiBox-root css-9whsf3&quot;]/div[@class=&quot;MuiFormControl-root css-13os6nc&quot;]/div[@class=&quot;MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary MuiInputBase-formControl MuiInputBase-sizeSmall css-nyy6b6&quot;]</value>
      <webElementGuid>a902061e-55bd-4fa4-8ad2-11f114a3dd2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addFarepayCard']/div/div/div[7]/div/div[2]/div/div/div</value>
      <webElementGuid>8555ea92-17a5-4bf9-bc66-931e949898a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Rider Classification'])[1]/following::div[2]</value>
      <webElementGuid>bb16ef48-3b03-49b7-abb1-ef1fa14c25d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::div[4]</value>
      <webElementGuid>fdc7e67d-274a-4d7d-9a13-1f160538118e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/div/div/div</value>
      <webElementGuid>6ceb81b2-3db2-4383-bae4-4519cf43510b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Senior/Disabled​' or . = 'Senior/Disabled​')]</value>
      <webElementGuid>473c4e7f-6ad3-481f-9206-c34372399c0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
