<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_card_text</name>
   <tag></tag>
   <elementGuidId>274a9e83-52e8-40ef-b510-f3161b57fc28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#XXXXXXXXXXX1003</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/preceding::span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;EiDgSn (XXXX XXXX XXX1 003)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8e329b0d-0f5b-40f8-96d2-39d3b23eda2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-label css-1c1r06l</value>
      <webElementGuid>4cf08a04-e6eb-49ba-9994-ad1dc922e5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>XXXXXXXXXXX1003</value>
      <webElementGuid>f1f4566f-10f6-463f-8d46-47a261845145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EiDgSn (XXXX XXXX XXX1 003)</value>
      <webElementGuid>ad0b0bc7-047a-4710-921f-8d35c788f0a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;XXXXXXXXXXX1003&quot;)</value>
      <webElementGuid>877c619f-8b92-41c6-a5b8-db8ae36b0b49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='XXXXXXXXXXX1003']</value>
      <webElementGuid>3512308d-eadc-4c86-aaa6-dceb00ecb95c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'XXXXXXXXXXX1003' and (text() = 'EiDgSn (XXXX XXXX XXX1 003)' or . = 'EiDgSn (XXXX XXXX XXX1 003)')]</value>
      <webElementGuid>5baa9994-9c0b-4a8d-ac15-75c87eb245a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PaymentsCard']/div/div/div/span</value>
      <webElementGuid>c06f1259-05a7-4143-8b2b-954285880dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/div/span</value>
      <webElementGuid>85a2f73a-649c-4b6f-8170-a5f60d935130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Saved Payments'])[1]/following::span[2]</value>
      <webElementGuid>87f3f0a9-126c-4e32-99ea-9a2b7461616e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/following::span[2]</value>
      <webElementGuid>53df0fbd-0e3c-446d-9e43-76ed2afdb2b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help &amp; Support'])[1]/preceding::span[2]</value>
      <webElementGuid>c24eef0e-23b5-4dd6-8320-771ea890b9ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/preceding::span[2]</value>
      <webElementGuid>5d9dfe47-4a4e-4538-a6a6-0e0ff74cca14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='EiDgSn']/parent::*</value>
      <webElementGuid>70872e04-6dad-4ea6-9e73-e33d0a6ea0f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
