<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SeniorDisabled</name>
   <tag></tag>
   <elementGuidId>5427fc45-475e-4d18-9eb2-ba996b14c385</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='addFarepayCard']/div/div/div[7]/div/div/div/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Senior/Disabled&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4de33b02-01e5-4161-a5a6-f40d8a6aae2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-value css-1hhxgbq</value>
      <webElementGuid>41748228-70c3-458d-8138-6bfebfc329f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Senior/Disabled-value</value>
      <webElementGuid>a109bf36-8409-4d0b-9102-49b55d708a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Senior/Disabled</value>
      <webElementGuid>1eac17a5-36cb-4d64-83b3-1153a46cf3ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Senior/Disabled-value&quot;)</value>
      <webElementGuid>b3f82738-2e97-471c-9621-403528213bc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='Senior/Disabled-value']</value>
      <webElementGuid>a2c8e4f3-fa3b-4d4e-8024-5d51a9d0864b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addFarepayCard']/div/div/div[7]/div/div/div/div/span[2]</value>
      <webElementGuid>15742d4a-6072-4662-ba3e-6c5dfdf7d487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rider Classification'])[1]/following::span[4]</value>
      <webElementGuid>69416860-7203-475c-aab9-239f9fa671d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NLR Underground Fare'])[1]/preceding::span[1]</value>
      <webElementGuid>fc582b7d-2ee0-4a8f-93d9-d752d04edcf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NLR Underground Fare'])[2]/preceding::span[3]</value>
      <webElementGuid>912da9f7-730d-40b9-8a86-89bd499a6205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Senior/Disabled']/parent::*</value>
      <webElementGuid>c99433da-fe8f-488c-904b-ddab61a9a145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/span[2]</value>
      <webElementGuid>9c299b4a-a5e5-477d-b3c7-95ee7dd8f2c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'Senior/Disabled-value' and (text() = 'Senior/Disabled' or . = 'Senior/Disabled')]</value>
      <webElementGuid>994d5ae5-918f-45ec-ab72-afc283b69cdf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
