<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_sVuzBH</name>
   <tag></tag>
   <elementGuidId>5af93484-e7a3-46ad-b9fe-2fc4212ea7c4</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='XXXXXXXXXXXX0286']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#XXXXXXXXXXXX0286</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'XXXXXXXXXXXX0286' and (text() = 'sVuzBH (XXXX XXXX XXXX 0286)' or . = 'sVuzBH (XXXX XXXX XXXX 0286)')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;sVuzBH (XXXX XXXX XXXX 0286)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>172fe1e7-c0e4-4790-a906-6ec1ed404517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-label css-1c1r06l</value>
      <webElementGuid>debb92c7-b7d4-483e-9617-66e60c62c968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>XXXXXXXXXXXX0286</value>
      <webElementGuid>aeabf560-5a96-4085-b4c6-eaedc9e660bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>sVuzBH (XXXX XXXX XXXX 0286)</value>
      <webElementGuid>9a7e7eb3-1345-4755-adec-062ee187e14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PaymentsCard&quot;)/div[@class=&quot;MuiCardContent-root css-1qw96cp&quot;]/div[@class=&quot;MuiBox-root css-lgj0h8&quot;]/div[@class=&quot;MuiBox-root css-16kngls&quot;]/span[@id=&quot;XXXXXXXXXXXX0286&quot;]</value>
      <webElementGuid>8f2aa954-f27d-4e8b-b639-3e9cc0c6e82d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='XXXXXXXXXXXX0286']</value>
      <webElementGuid>774d34a6-df42-4a36-b4c8-6e1b9baf2f3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PaymentsCard']/div/div/div/span</value>
      <webElementGuid>9cafc7d8-a1b4-4218-b2bd-924d4bf52e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Saved Payments'])[1]/following::span[2]</value>
      <webElementGuid>b8ea1cb0-1749-46bc-b04f-e4475ea4d370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/following::span[2]</value>
      <webElementGuid>64c8aa9c-0719-46fe-a1fe-c81fb67ed707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help &amp; Support'])[1]/preceding::span[3]</value>
      <webElementGuid>7284375a-b709-4683-84f1-1584e183f1e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='sVuzBH']/parent::*</value>
      <webElementGuid>508c248c-6de0-4241-a6e0-8045415f799c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/div/span</value>
      <webElementGuid>0cf9a774-ef72-44c0-8645-1ffc91859c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'XXXXXXXXXXXX0286' and (text() = 'sVuzBH (XXXX XXXX XXXX 0286)' or . = 'sVuzBH (XXXX XXXX XXXX 0286)')]</value>
      <webElementGuid>bf6e5bfb-c81c-44f8-88c6-6c0508c6558e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
